Microbe_Name
Nitrososphaera viennensis
Nitrosocosmicus oleophilus
Nitrosocosmicus sp.
Nitrososphaera sp.
Methanobacterium sp.
Methanocella sp.
Methanoperedens sp.
Methanosaeta sp.
Methanosarcina mazei
Methanosarcina sp.
Koribacter sp.
Bryobacter sp.
Paludibaculum sp.
Solibacter sp.
Aridibacter sp.
Blastocatella sp.
Stenotrophobacter sp.
Arenimicrobium luteum
Luteitalea pratensis
Luteitalea sp.
Vicinamibacter sp.
Iamia sp.
Ilumatobacter sp.
Mycobacterium bacteremicum
Mycobacterium elephantis
Mycobacterium holsaticum
Mycobacterium sp.
Mycobacterium tusciae
Nocardia farcinica
Nocardia sp.
Rhodococcus sp.
Acidothermus sp.
Cryptosporangium sp.
Jatrophihabitans sp.
Blastococcus aggregatus
Blastococcus jejuensis
Blastococcus sp.
Geodermatophilus daqingensis
Geodermatophilus sp.
Geodermatophilus tzadiensis
Nakamurella silvestris
Nakamurella sp.
Glycomyces algeriensis
Kineosporia sp.
Quadrisphaera granulorum
Quadrisphaera sp.
Beutenbergia cavernae
Cellulomonas cellasea
Cellulomonas hominis
Cellulomonas sp.
Aquipuribacter sp.
Intrasporangium sp.
Janibacter alkaliphilus
Lapillicoccus jejuensis
Ornithinibacter aureus
Ornithinimicrobium sp.
Pedococcus dokdonensis
Phycicoccus elongatus
Agromyces flavus
Agromyces sp.
Curtobacterium oceanosedimentum
Microbacterium oleivorans
Microbacterium paraoxydans
Kocuria rosea
Pseudarthrobacter oxydans
Sinomonas sp.
Isoptericola halotolerans
Actinoplanes derwentensis
Actinoplanes friuliensis
Actinoplanes globisporus
Actinoplanes philippinensis
Actinoplanes rishiriensis
Actinoplanes sarveparensis
Actinoplanes sp.
Asanoa sp.
Catellatospora bangladeshensis
Catellatospora sp.
Catelliglobosispora koreensis
Catenuloplanes sp.
Dactylosporangium sp.
Hamadaea sp.
Krasilnikovia sp.
Longispora sp.
Luedemannella sp.
Micromonospora coxensis
Micromonospora narathiwatensis
Micromonospora sp.
Phytohabitans sp.
Planosporangium flavigriseum
Planosporangium sp.
Plantactinospora mayteni
Plantactinospora sp.
Polymorphospora rubra
Rhizocola sp.
Salinispora sp.
Virgisporangium aliadipatigenens
Virgisporangium ochraceum
Virgisporangium sp.
Micromonospora phaseoli
Aeromicrobium ginsengisoli
Aeromicrobium sp.
Kribbella endophytica
Kribbella sp.
Marmoricola bigeumensis
Marmoricola sp.
Marmoricola terrae
Nocardioides albus
Nocardioides alpinus
Nocardioides aromaticivorans
Nocardioides dilutus
Nocardioides exalbidus
Nocardioides halotolerans
Nocardioides hankookensis
Nocardioides iriomotensis
Nocardioides kandeliae
Nocardioides phosphati
Nocardioides pyridinolyticus
Nocardioides sp.
Microlunatus lucidus
Haloactinopolyspora sp.
Jiangella muralis
Microlunatus panaciterrae
Microlunatus sp.
Propionicicella sp.
Actinomycetospora sp.
Actinophytocola sp.
Crossiella sp.
Lentzea aerocolonigenes
Pseudonocardia endophytica
Pseudonocardia halophobica
Pseudonocardia hispaniensis
Pseudonocardia sp.
Pseudonocardia zijingensis
Saccharopolyspora erythraea
Saccharopolyspora shandongensis
Saccharothrix sp.
Streptomyces albidoflavus
Streptomyces avermitilis
Streptomyces capparidis
Streptomyces haliclonae
Streptomyces macrosporus
Streptomyces niveus
Streptomyces polychromogenes
Streptomyces scabiei
Streptomyces sp.
Streptomyces yanglinensis
Streptomyces zaomyceticus
Yinghuangia aomiensis
Herbidospora cretacea
Microbispora corallina
Microtetraspora malaysiensis
Nonomuraea rhodomycinica
Sinosporangium sp.
Sphaerisporangium melleum
Sphaerisporangium sp.
Streptosporangium sp.
Actinoallomurus vinaceus
Actinomadura sp.
Actinomadura vinacea
Rubrobacter sp.
Gaiella sp.
Conexibacter sp.
Parviterribacter kavangonensis
Parviterribacter multiflagellatus
Parviterribacter sp.
Solirubrobacter phytolaccae
Solirubrobacter soli
Solirubrobacter sp.
Chthonomonas sp.
Chitinophaga sp.
Cnuella sp.
Dinghuibacter sp.
Ferruginibacter sp.
Flaviaesturariibacter sp.
Flavihumibacter sp.
Flavisolibacter ginsengisoli
Flavisolibacter ginsengiterrae
Flavisolibacter metallilatus
Flavisolibacter sp.
Flavisolibacter swuensis
Flavisolibacter tropicus
Flavitalea gansuensis
Flavitalea sp.
Niastella hibisci
Niastella populi
Niastella sp.
Niastella vici
Parasegetibacter sp.
Parasegetibacter terrae
Pseudoflavitalea sp.
Puia sp.
Segetibacter koreensis
Terrimonas lutea
Terrimonas sp.
Cytophaga sp.
Rhodocytophaga aerolata
Rhodocytophaga sp.
Sporocytophaga sp.
Adhaeribacter sp.
Hassallia sp.
Ohtaekwangia sp.
Nibrella saemangeumensis
Fluviicola hefeinensis
Flavobacterium sp.
Peredibacter sp.
Peredibacter starrii
Bdellovibrio sp.
Oligoflexus sp.
Anaerolinea sp.
Leptolinea sp.
Longilinea sp.
Litorilinea sp.
Chloronema sp.
Chloroploca sp.
Herpetosiphon sp.
Kallotenue sp.
Nitrolancea hollandica
Dehalococcoides sp.
Anabaena azotica
Anabaena constricta
Desmonostoc muscorum
Nostoc paludosum
Nostoc sp.
Scytonema sp.
Anabaena sphaerica
Tolypothrix sp.
Pantanalinema rosaneae
Desulfobacca sp.
Desulfatiglans sp.
Desulfatitalea sp.
Desulfocapsa sp.
Geoalkalibacter sp.
Citrifermentans sp.
Geobacter bemidjiensis
Geobacter sp.
Desulfovirga sp.
Syntrophobacter sp.
Endomicrobium sp.
Entotheonella sp.
Tumebacillus sp.
Aneurinibacillus sp.
Anaerobacillus sp.
Bacillus acidiceler
Bacillus andreesenii
Bacillus benzoevorans
Bacillus cereus
Bacillus circulans
Bacillus funiculus
Bacillus gottheilii
Bacillus hackensackii
Bacillus halmapalus
Bacillus halotolerans
Bacillus horti
Bacillus korlensis
Bacillus longiquaesitum
Bacillus massiliogorillae
Bacillus megaterium
Bacillus methanolicus
Bacillus oceanisediminis
Bacillus pocheonensis
Bacillus pumilus
Bacillus simplex
Bacillus sp.
Bacillus subterraneus
Cytobacillus firmus
Fictibacillus nanhaiensis
Mesobacillus foraminis
Metabacillus fastidiosus
Metabacillus indicus
Metabacillus litoralis
Metabacillus niabensis
Neobacillus niacini
Terribacillus sp.
Domibacillus indicus
Domibacillus sp.
Lysinibacillus fusiformis
Sporosarcina sp.
Brevibacillus ginsengisoli
Brevibacillus laterosporus
Brevibacillus sp.
Lumbricincola sp.
Ammoniphilus resinae
Ammoniphilus sp.
Cohnella sp.
Cohnella yongneupensis
Paenibacillus barcinonensis
Paenibacillus cellulosilyticus
Paenibacillus daejeonensis
Paenibacillus ehimensis
Paenibacillus filicis
Paenibacillus gansuensis
Paenibacillus glycanilyticus
Paenibacillus gorillae
Paenibacillus harenae
Paenibacillus lautus
Paenibacillus massiliensis
Paenibacillus mucilaginosus
Paenibacillus polymyxa
Paenibacillus prosopidis
Paenibacillus sp.
Paenibacillus typhae
Baia sp.
Shimazuella kribbensis
Shimazuella sp.
Thermoflavimicrobium sp.
Fervidicella sp.
Fonticella sp.
Clostridium polyendosporum
Clostridium beijerinckii
Clostridium cavendishii
Clostridium hydrogeniformans
Clostridium hydrogeniproducens
Clostridium magnum
Clostridium pasteurianum
Clostridium putrefaciens
Clostridium sp.
Clostridium tunisiense
Clostridium vulturis
Oxobacter sp.
Gracilibacter sp.
Lutispora sp.
Anaerocolumna sp.
Anaerosporobacter sp.
Herbinix sp.
Lachnoclostridium sp.
Mobilitalea sp.
Acetivibrio sp.
Hungateiclostridium aldrichii
Hungateiclostridium cellulolyticum
Anaerobacterium sp.
Ruminiclostridium cellobioparum
Ruminiclostridium sp.
Alkaliphilus peptidifermentans
Paraclostridium sp.
Romboutsia maritimum
Sporacetigenium mesophilum
Anaerosolibacter carboniphilus
Geosporobacter ferrireducens
Salimesophilobacter sp.
Thermincola sp.
Desulfofarcimen sp.
Desulfotomaculum aquiferis
Desulfotomaculum sp.
Hydrogenispora sp.
Anaerospora sp.
Sporomusa ovata
Sporomusa sp.
Gemmatimonas sp.
Gemmatirosa sp.
Roseisolibacter agri
Roseisolibacter sp.
Longimicrobium sp.
Anaeromyxobacter sp.
Aggregicoccus edonensis
Aggregicoccus sp.
Archangium gephyra
Archangium sp.
Cystobacter gracilis
Myxococcus fulvus
Myxococcus sp.
Stigmatella sp.
Vulgatibacter sp.
Haliangium sp.
Kofleria flava
Enhygromyxa sp.
Nannocystis sp.
Pseudenhygromyxa sp.
Phaselicystis flava
Phaselicystis sp.
Aetherobacter sp.
Chondromyces pediculatus
Jahnella thaxteri
Labilithrix luteola
Minicystis rosea
Minicystis sp.
Pajaroellobacter sp.
Polyangium fumosum
Polyangium sorediatum
Polyangium sp.
Sorangium cellulosum
Sorangium sp.
Sandaracinus amylolyticus
Leptospirillum sp.
Nitrospira japonica
Nitrospira nitrosa
Nitrospira sp.
Fimbriiglobus sp.
Gemmata massiliana
Gemmata sp.
Aquisphaera sp.
Paludisphaera sp.
Singulisphaera sp.
Tundrisphaera sp.
Blastopirellula sp.
Pirellula sp.
Rhodopirellula sp.
Belnapia sp.
Paracraurococcus ruber
Rhodovarius sp.
Roseomonas sp.
Roseomonas wooponensis
Acuticoccus sp.
Azospirillum canadense
Azospirillum sp.
Desertibacter roseus
Skermanella aerolata
Skermanella sp.
Phenylobacterium mobile
Phenylobacterium sp.
Hirschia sp.
Defluviicoccus sp.
Dongia sp.
Reyranella sp.
Bosea sp.
Bosea thiooxidans
Bosea vestrisii
Methylobacterium currus
Methylobacterium iners
Methylobacterium isbiliense
Methylobacterium organophilum
Methylobacterium radiotolerans
Methylocapsa sp.
Methylorosula sp.
Methylosinus trichosporium
Microvirga aerilata
Microvirga guangxiensis
Microvirga massiliensis
Microvirga ossetica
Microvirga sp.
Microvirga vignae
Psychroglaciecola sp.
Salinarimonas sp.
Devosia sp.
Hyphomicrobium sp.
Pedomicrobium sp.
Labrys sp.
Methyloceanibacter sp.
Methylopila sp.
Chthonobacter sp.
Prosthecomicrobium sp.
Agrobacterium albertimagni
Rhizobium sp.
Aminobacter sp.
Ensifer adhaerens
Sinorhizobium meliloti
Mesorhizobium albiziae
Mesorhizobium olivaresii
Mesorhizobium sp.
Shinella kummerowiae
Sinorhizobium terangae
Alsobacter metallidurans
Bauldia sp.
Nordella sp.
Phreatobacter sp.
Rhodomicrobium sp.
Labrenzia suaedae
Bradyrhizobium canariense
Bradyrhizobium cytisi
Bradyrhizobium sp.
Bradyrhizobium yuanmingense
Nitrobacter vulgaris
Pseudolabrys sp.
Pseudorhodoplanes sp.
Rhodoplanes elegans
Rhodoplanes sp.
Starkeya novella
Albimonas pacifica
Amaricoccus sp.
Limibaculum sp.
Rubellimicrobium sp.
Tabrizicola sp.
Magnetospirillum sp.
Altererythrobacter sp.
Hephaestia sp.
Novosphingobium sp.
Novosphingobium taihuense
Porphyrobacter donghaensis
Sphingomonas changbaiensis
Sphingomonas daechungensis
Sphingomonas humi
Sphingomonas oryziterrae
Sphingomonas sp.
Alysiosphaera sp.
Cupriavidus respiraculi
Cupriavidus taiwanensis
Lautropia sp.
Acidovorax konjaci
Acidovorax oryzae
Acidovorax sp.
Azohydromonas sp.
Caldimonas manganoxidans
Comamonas sp.
Ideonella sp.
Paucibacter toxinivorans
Piscinibacter sp.
Ramlibacter ginsenosidimutans
Ramlibacter sp.
Rhizobacter sp.
Xenophilus aerolatus
Sideroxydans paludicola
Nitrosovibrio tenuis
Massilia sp.
Massilia timonae
Noviherbaspirillum agri
Noviherbaspirillum sp.
Oxalicibacterium sp.
Pseudoduganella sp.
Accumulibacter sp.
Azoarcus sp.
Azoarcus taiwanensis
Azonexus caeni
Azospira restricta
Azospira sp.
Azovibrio sp.
Dechloromonas agitata
Georgfuchsia sp.
Aquicella sp.
Aeromonas veronii
Klebsiella pneumoniae
Acidibacter sp.
Legionella sp.
Methylocaldum sp.
Methylobacter luteus
Methylobacter sp.
Methylomicrobium sp.
Cellvibrio mixtus
Azotobacter nigricans
Azotobacter salinestris
Azotobacter tropicalis
Pseudomonas alcaligenes
Pseudomonas peli
Pseudomonas putida
Povalibacter uvarum
Steroidobacter flavus
Steroidobacter sp.
Ahniella sp.
Dokdonella ginsengisoli
Dokdonella sp.
Dyella sp.
Fulvimonas yonginensis
Arenimonas daechungensis
Arenimonas sp.
Lysobacter brunescens
Lysobacter dokdonensis
Lysobacter fragariae
Lysobacter oryzae
Lysobacter sp.
Lysobacter yangpyeongensis
Pseudoxanthomonas indica
Pseudoxanthomonas mexicana
Thermomonas sp.
Sumerlaea sp.
Chthoniobacter sp.
Udaeobacter sp.
Xiphinematobacter sp.
Cephaloticoccus sp.
Lacunisphaera sp.
Opitutus sp.
Luteolibacter flavescens
Luteolibacter sp.
Roseimicrobium gellanilyticum
Roseimicrobium sp.
